# Generated by Django 2.2.5 on 2020-02-25 21:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', help_text='Post title', max_length=1024)),
                ('content', models.TextField(default='')),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('image', models.ImageField(default=None, upload_to='')),
                ('post_type', models.CharField(choices=[(0, 'Whats on (Feed post)'), (1, 'Event (Impact post)')], default=(0, 'Whats on (Feed post)'), max_length=23)),
                ('required_access', models.CharField(choices=[(0, 'Everyone'), (1, 'Impact member'), (2, 'Staff')], default=(0, 'Everyone'), max_length=15)),
                ('is_visible', models.BooleanField(default=True, help_text='Visibility, toggle instead of deleting')),
                ('post_date', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('last_edit', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('post_date', 'last_edit'),
            },
        ),
    ]
