version: '3'

services:

    frontend:
        build: ./ImpactWebsiteFrontend
        restart: always
        depends_on:
            - web
        expose:
            - "3000"

    nginx:
        build: ./nginx
        restart: always
        ports:
            - "81:80"
        depends_on:
            - web
            
    db:
        image: postgres
        restart: always
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
              - POSTGRES_USER=${SQL_USER}
              - POSTGRES_PASSWORD=${SQL_PASSWORD}
              - POSTGRES_DB=${SQL_DATABASE}
    web:
        build: .
        volumes:
            - .:/code

        expose:
            - "8000"
              #        restart: always

        depends_on:
            - db
        
volumes:
    postgres_data:
